[variables]
NIXPACKS_NO_MUSL = "1"

[phases.setup]
nixPkgs = ["R"]

[phases.install]
cmd = "R -e \"install.packages(c('plumber', 'caret', 'dplyr', 'pROC', 'ranger', 'jsonlite'), repos='https://cran.rstudio.com/')\""

[phases.build]
cmd = "echo 'Build complete'"

[start]
cmd = "R -e \"pr <- plumber::plumb('cancer_api.R'); pr$run(host='0.0.0.0', port=as.numeric(Sys.getenv('PORT', 8000)))\""